// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbmgduqrwjlcxzmjjrhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibWdkdXFyd2psY3h6bWpqcmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjM5MDYsImV4cCI6MjA1ODE5OTkwNn0.BOQ4vtJ0S-w4yxsziyMu1dGZxcIv_vxdmczKSyHr05Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);